"""followers

Revision ID: 712329e0f918
Revises: b2a0993fa53b
Create Date: 2018-07-08 10:57:13.933294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712329e0f918'
down_revision = 'b2a0993fa53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
